### ISSUE TITLE
[2pts] Log In Form

### ISSUE THREAD

**Issue by Felipe-Perez-Ferraro** [Felipe-Perez-Ferraro/final_capstone_front#1]
The user logs in to the website, only by typing the username (a proper authenticated login is a requirement if your group is made of 5 people).

**Comment by Felipe-Perez-Ferraro** [comment]
The user logs in to the website, only by typing the username (a proper authenticated login is a requirement if your group is made of 5 people).

**Comment by hajnaloltyan** [comment]
The PR in the back-end corresponding with this front-end issues: https://github.com/Felipe-Perez-Ferraro/final_capstone_back/pull/6
